### ISSUE TITLE
Metoda określania czy ma być wygenerowany nowy numer

### ISSUE THREAD

**Issue by michal-bielinski** [kwadrat-informatyczny/szczesliwy-numerek-server#5]
Demand:
- Losowanie od wtorku do niedzieli (20:00),

Future
- Nie losować w święta, dni wolne, ferie, wakacje.

**Comment by pawel-jedrzejczak** [comment]
A nie od niedzieli do czwartku?

**Comment by JPaweu** [comment]
Czyli mój 'program' ma zwracać na samym końcu "data kolejnego losowania", czyli sam dzień kiedy ma się wylosować nowy numer? I wtedy ktoś od "Metoda określania daty kolejnego losowania [Issue #6]" już to jakoś interpretuje tak żeby program działał? 
Dobrze rozumiem? 🤔

**Comment by michal-bielinski** [comment]
DONE!
