### ISSUE TITLE
Metoda określania daty kolejnego losowania

### ISSUE THREAD

**Issue by michal-bielinski** [kwadrat-informatyczny/szczesliwy-numerek-server#6]

**Comment by RemekZ** [comment]
zrobie

**Comment by michal-bielinski** [comment]
@RemekZ metoda do napisania (nawet w konsole Chrome F12) powinna zwracać nam dzień kolejnego losowania. 

function getNextDrawTime() {

}

W pierwszej fazie zróbmy tak, że losowanie jest od niedzieli do czwartku o 20:00. Więc w czwartek o 20:01 funkcja powinna zwrócić niedzielę 20:00, w niedzielę o 20:01 poniedziałek 20:00 itd.

**Comment by michal-bielinski** [comment]
Done!
